import "./globals.css";
import { Inter, Poppins } from "next/font/google";
import Providers from "./providers";
import Header from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";

export const metadata = {
  title: "JR Tutoring",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"], // add more weights if needed
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Providers>
          <Header />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
