[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Your Name <ri1jgo0l@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
asgiref = "3.8.1"
attrs = "25.3.0"
dj-database-url = "2.3.0"
django = "5.2"
django-cors-headers = "4.7.0"
djangorestframework = "3.16.0"
djangorestframework-simplejwt = "5.5.0"
drf-spectacular = "0.28.0"
gunicorn = "23.0.0"
inflection = "0.5.1"
jsonschema = "4.23.0"
jsonschema-specifications = "2025.4.1"
packaging = "25.0"
psycopg2-binary = "2.9.10"
pyjwt = "2.9.0"
pyyaml = "6.0.2"
referencing = "0.36.2"
rpds-py = "0.24.0"
sqlparse = "0.5.3"
typing-extensions = "4.13.2"
uritemplate = "4.1.1"
python-dotenv = "^1.1.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
