# Generated by Django 5.2 on 2025-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='users.subject'),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='tutees',
            field=models.ManyToManyField(blank=True, null=True, related_name='tutees', to='users.tuteeprofile'),
        ),
    ]
