# Generated by Django 5.2 on 2025-05-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_tutorprofile_subjects_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuteeprofile',
            old_name='tutor',
            new_name='tutors',
        ),
    ]
