# Generated by Django 5.2 on 2025-05-22 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_tutor_tuteeprofile_tutors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='rating',
            field=models.DecimalField(db_index=True, decimal_places=1, default=2.5, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
