# Generated by Django 5.2 on 2025-05-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_tutorprofile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='users.subject'),
        ),
    ]
