# Generated by Django 5.2 on 2025-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_tutorprofile_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='subjects', to='users.subject'),
        ),
    ]
