#!/bin/sh

echo "🌀 Activating Python virtualenv..."
cd backend || exit 1
. venv/bin/activate || exit 1

echo "🌀 Generating OpenAPI schema..."
python3 manage.py spectacular --file ../openapi/schema.yaml || exit 1

echo "🔄 Running Kubb to sync frontend hooks & types..."
cd ../frontend || exit 1
npx kubb || exit 1

echo "✅ All good! Pushing..."
