#!/bin/sh

echo "🌀 Generating OpenAPI schema..."
cd backend || exit 1
poetry run python manage.py spectacular --file ../openapi/schema.yaml || exit 1

echo "🔄 Running Kubb to sync frontend hooks & types..."
cd ../frontend || exit 1
npx kubb || exit 1

echo "✅ All good! Pushing..."
