# Generated by Django 5.1.7 on 2025-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testmodel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel2',
            name='age',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
    ]
