# Generated by Django 5.1.7 on 2025-03-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_testmodel2_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel2',
            name='age',
        ),
    ]
